### ISSUE TITLE
Naming error on src/plugin.css? 

### ISSUE THREAD

**Issue by oscarvajalmora** [mister-ben/videojs-seek-buttons#71]
Hi! I'm using this plugin into a react app with video js. My question is, why the src/plugin.css file has .css extension even if this has sass code inside it? Should it has .scss extension instead?

**Comment by mister-ben** [comment]
The project is using [postcss](https://github.com/postcss/postcss) rather than sass. The nesting used in that css is supported by both, so it's probably valid scss too in its current state. Other sass features wouldn't necessarily work.

The sass comment in the file is erroneous, at one point this was using libsass and the current css was converted from the old scss file.
